### Methods(part 2)

In [1]:
import numpy as np

In [7]:
#1 - .array() > most useful
# take a python list > numpy array
array_one = np.array(
    [1,2,3]
)

In [8]:
array_one

array([1, 2, 3])

In [12]:
# some methods > self filling data > array
#2 - .empty() > take shape > (row,colunm) and dtype > array > 2d
# dtype default > float64 > dtype = x , just x
array_two = np.empty((3,4))

In [10]:
array_two

array([[8.18157066e-312, 3.16202013e-322, 0.00000000e+000,
        0.00000000e+000],
       [1.11260619e-306, 5.40495561e-038, 3.11352059e-032,
        1.53513189e-075],
       [1.93443297e-076, 1.15345030e-071, 1.20080587e-071,
        4.42245018e-062]])

In [11]:
array_two.ndim

2

In [18]:
array_three = np.empty((3,4),dtype=np.uint8) # just + and 0

In [14]:
array_three

array([[1, 1, 0, 0],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=uint8)

In [17]:
array_four = np.empty((3,4),dtype=np.int8) # - and + and 0

In [16]:
array_four

array([[  48,    8,   78, -113],
       [-127,    1,    0,    0],
       [   0,    0,    0,    0]], dtype=int8)

In [19]:
# like method > take a prototpye and create an array based on that

In [77]:
# prototype > create arrays like this
array_five = ([1,2,3],[4,5,6])
# You can put + and - data in prototype
# if all + > sempty_like() > just + but also - > in _like both + and -
# create prototype without methods :
# var_name = ((data)) , [[data]] ([data]) , [(data)] >>> all 2D
# if just one () or [] > 1D
# nested () or [] > more axises(dimentions)
# no givin shape > create as shape of prototype
# you can change the shape
array_six = np.empty_like(array_five)
array_six

array([[-1890711504,         385,           0],
       [          0,      131074, -2147483648]])

In [78]:
# numner of elements in prototype > fit in new shape
array_seven = np.empty_like(array_five,shape=(3,2))
array_seven

array([[-1891166224,         385],
       [          0,           0],
       [          1,  1629516911]])

In [83]:
# .eye() > 2D > main dimeter(\) is 1 and else where is 0 > till the shape is square
# not square > last colunm al zero
# n > number of rows(required)
# m > number of colunms(optional) > if not > will pick n as m
# k < where to start put 1 > default index=0,0(because is 2d) > move forward in order of indexing
array_eight = np.eye(4)

In [80]:
array_eight

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [82]:
array_nine = np.eye(4,5)
array_nine

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [87]:
array_ten = np.eye(4,5,1)
array_ten

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [88]:
array_eleven = np.eye(4,5,2)
array_eleven

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [96]:
array_twelve = np.eye(4,5,-1)
array_twelve
# dimeter 1
# start from <= -1 >>>> one row below at index 0

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [100]:
# is similar to > .eye() > but always suqare
# not takeig colunm just row (n)
# number of rows and colunm = n
# you can chage dtype
array_thirten = np.identity(4)
array_thirten

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [103]:
# .ones() > all 1
# take dtype and shape > create base on shape
array_fourteen = np.ones((2,3))
array_fourteen

array([[1., 1., 1.],
       [1., 1., 1.]])

In [106]:
array_fifteen = np.ones((2,3,4))
array_fifteen
# we have .ones_like()

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [109]:
# all 0
# take dtype and shape > create base on shape
array_sixteen = np.zeros((2,3))
array_sixteen
# we have .zeros_like()

array([[0., 0., 0.],
       [0., 0., 0.]])

In [110]:
# .full() > fill array by our data
# take dtype and shape and fill value > create base on shape
array_seventeen = np.full((3,3),8)
array_seventeen
# we have .full_like()

array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]])

In [115]:
# useful methof
# .arange()
# take start and stop > array > you can give step our dtype
# stope is required and others are optional
# just stop > from 0 to stop -1 > (stop) or ((stop))
array_eighteen = np.arange(90)
array_eighteen

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89])

In [119]:
# with start > (start,stop,step)
array_ninteen = np.arange(10,90)
array_ninteen
# change structure > use .reshape

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89])

In [125]:
# pay attention to number of elements > array.size() > fit all elements
array_twenty = array_ninteen.reshape((8,10))
array_twenty

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89]])

In [127]:
# np.matrix() > create matrix
# not recommended by numpy > use other array creators