# Methods(part 1)

In [1]:
import numpy as np

In [3]:
array_one = np.array(
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
)

In [6]:
# Number of axis' or dimention(s) > axis = dimention
array_one.ndim

2

In [7]:
# number of all elements in array
array_one.size

9

In [8]:
# The structure of array > (raw,colunm) > (axis 0 , axis 1)
array_one.shape

(3, 3)

In [16]:
# Change the structure of array(create new array-not changing the original array) > fit all elements > multiple of number of elements
# array_one.reshape(raw,colunm)
array_one.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [10]:
array_one.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [11]:
array_two = np.array(
    [
        [1,2,3],
        [4,5,6],
    ]
)
array_two.shape

(2, 3)

In [12]:
array_two.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [13]:
array_three = array_two.reshape(3,2)

In [14]:
array_two

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
array_three

array([[1, 2],
       [3, 4],
       [5, 6]])

In [18]:
# Sclicing(normal)
array_one[0][1]

np.int64(2)

In [19]:
# Numpy recommendation
# array_name[raw,colunm]
array_one[0,2]

np.int64(3)

In [20]:
# Range > array_name[raw_start_index:raw_end_index]
# Raw_end_index is not included > [raw_start_index:raw_end_index-1]
# 0 is optional
array_one[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
array_one[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
# From start to end
array_one[:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
# Merge or splite
# Note : no matter use [] or ()
array_four = np.array((11,12,33))
array_four.ndim

1

In [23]:
# Merging vertical
# np.vstack((a,b)) > will add b at the end of a vertically as a row
# pay attention about dimentions limit in vstack and hstack
np.vstack((array_one,array_four))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 33]])

In [24]:
np.vstack((array_four,array_one))

array([[11, 12, 33],
       [ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [25]:
array_five = np.array(
    [
        [11],
        [12],
        [23]
    ]
)

In [26]:
# np.hstack((a,b)) > will add b at the end of a horizontally as a colounm
# pay attention about dimentions limit in vstack and hstack
np.hstack((array_one,array_five))

array([[ 1,  2,  3, 11],
       [ 4,  5,  6, 12],
       [ 7,  8,  9, 23]])

In [54]:
np.hstack((array_five,array_one))

array([[11,  1,  2,  3],
       [12,  4,  5,  6],
       [23,  7,  8,  9]])

In [58]:
# Both vstack and hstack together
# pay attention about dimention limits in concatenate
# array_name.concatenate((a,b),axis=0/1) > won't with 1D?
# axis = 1 > will add b at the end of a horizontally as a colunm
# axis = 0 > will add b at the end of a vertically as a row
np.concatenate((array_one,array_five),axis=1)

array([[ 1,  2,  3, 11],
       [ 4,  5,  6, 12],
       [ 7,  8,  9, 23]])

In [56]:
np.concatenate((array_five,array_one),axis=1)

array([[11,  1,  2,  3],
       [12,  4,  5,  6],
       [23,  7,  8,  9]])

In [59]:
array_six = np.array(
    [
        [11,12,33]
    ]
)

In [60]:
np.concatenate((array_one,array_six),axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 33]])

In [62]:
np.concatenate((array_six,array_one),axis=0)

array([[11, 12, 33],
       [ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [ ]:
# split
# np.vsplit(array,number of splits)
# number of splits must match to number to elements > number of splits // number to elements == 0
np.vsplit() # spliting rows
np.hsplit() # spliting colunms

In [63]:
np.vsplit(array_one,3)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

In [65]:
np.hsplit(array_one,3)

[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]

In [68]:
# sorting array from biggest to smallest
array_seven = np.array(
    (
        (1,3,2),
        (6,5,4),
        (8,7,9)
    )
)
np.sort(array_seven)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [75]:
# take a copy from array 
# 1- .copy() > full copy of array > create a new array
# 2- .view() > take array and pass it > no change > point to that array

In [76]:
# if you make changes in .copy() , will have no effect on main array

In [89]:
array_eight = array_one.copy()

In [77]:
# if you make any changes in .viwe , main array will be changed

In [90]:
array_nine = array_one.view()

In [91]:
array_eight

array([[ 1, 66,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [74]:
array_nine

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [78]:
array_eight[0,1] = 22

In [79]:
print(array_one)
print("*************")
print(array_eight)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
*************
[[ 1 22  3]
 [ 4  5  6]
 [ 7  8  9]]


In [81]:
array_nine[0,1] = 66

In [82]:
print(array_one)
print("*************")
print(array_nine)

[[ 1 66  3]
 [ 4  5  6]
 [ 7  8  9]]
*************
[[ 1 66  3]
 [ 4  5  6]
 [ 7  8  9]]


In [94]:
# How find out an array is copy or view ?
# .base > retutn the main used array (view) > whicj
# .base > nothing will be returned > no base > is a new array

In [93]:
array_eight.base

In [95]:
print(array_eight.base)

None


In [87]:
array_nine.base

array([[ 1, 66,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [96]:
print(array_nine.base)

[[ 1 66  3]
 [ 4  5  6]
 [ 7  8  9]]
