# Methods(part 3)

In [1]:
import numpy as np

In [26]:
# To Create numbers which have even space with each other
# What does is take ? start ,  stop , num
# num means how many munbers you want and by default is 50
# This gives us 40 numbers from 1 to 99 with equal space
# stop is included and it's from start to stop
# Which means that it has endpoint parameter and is True by default and stop will be shown but if you set it False stop will not be included
# If you want to see the space set retstep as True which is False by default
np.linspace(1,99,num=40)

array([ 1.        ,  3.51282051,  6.02564103,  8.53846154, 11.05128205,
       13.56410256, 16.07692308, 18.58974359, 21.1025641 , 23.61538462,
       26.12820513, 28.64102564, 31.15384615, 33.66666667, 36.17948718,
       38.69230769, 41.20512821, 43.71794872, 46.23076923, 48.74358974,
       51.25641026, 53.76923077, 56.28205128, 58.79487179, 61.30769231,
       63.82051282, 66.33333333, 68.84615385, 71.35897436, 73.87179487,
       76.38461538, 78.8974359 , 81.41025641, 83.92307692, 86.43589744,
       88.94871795, 91.46153846, 93.97435897, 96.48717949, 99.        ])

In [27]:
np.linspace(1,99,num=40,retstep=True)

(array([ 1.        ,  3.51282051,  6.02564103,  8.53846154, 11.05128205,
        13.56410256, 16.07692308, 18.58974359, 21.1025641 , 23.61538462,
        26.12820513, 28.64102564, 31.15384615, 33.66666667, 36.17948718,
        38.69230769, 41.20512821, 43.71794872, 46.23076923, 48.74358974,
        51.25641026, 53.76923077, 56.28205128, 58.79487179, 61.30769231,
        63.82051282, 66.33333333, 68.84615385, 71.35897436, 73.87179487,
        76.38461538, 78.8974359 , 81.41025641, 83.92307692, 86.43589744,
        88.94871795, 91.46153846, 93.97435897, 96.48717949, 99.        ]),
 np.float64(2.5128205128205128))

In [13]:
# This makes an 1D array from given iterable(for loops)
# iterable(for loops)
# dtype is required for this method
list = [i*i for i in range(1,11)]
print(list)
np.fromiter(list,dtype=np.int8)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int8)

In [16]:
# Use string instead and takes a string and save its data as an array
# dtype is float by default, but it can be changed
# for example > saving data in string
# It has sep parameter which says what is the space of items in the string
# for seperating data
# you must always give seperator to prevent possible errors
np.fromstring('1,2,3,4,5,6',dtype=np.int8,sep=',')

array([1, 2, 3, 4, 5, 6], dtype=int8)

In [18]:
# without seperator, it returns non-sense value and shows an error
np.fromstring('1,2,3,4,5,6',dtype=np.int8)

C:\Users\veniz\AppData\Local\Temp\ipykernel_3168\3880544747.py:2: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  np.fromstring('1,2,3,4,5,6',dtype=np.int8)


array([49, 44, 50, 44, 51, 44, 52, 44, 53, 44, 54], dtype=int8)

In [20]:
# Convert degree to radian and vice-versa
# This converts degree to radian and takes degree
np.radians(180)

np.float64(3.141592653589793)

In [21]:
np.radians(360)

np.float64(6.283185307179586)

In [24]:
# This converts radian to degree and takes radian as input
np.degrees(2.345)

np.float64(134.35860295817807)

In [25]:
np.degrees(2)

np.float64(114.59155902616465)