# Broadcasting

In [1]:
import numpy as np

In [4]:
# Logical and mathematical operations on arrays in numpy
array_one = np.array(
    [
        [1,2,3]
    ]
)
array_two = np.array(
    [
        [4,5,6]
    ]
)

In [8]:
# plus their elements [[1+4,2+5,3+6]] >> element wise > work on elements not the
# arrays themself
array_one + array_two

array([[5, 7, 9]])

In [13]:
# on all elements
print(array_one + 1)
print(array_one -1)
print(array_one - array_two)

[[2 3 4]]
[[0 1 2]]
[[-3 -3 -3]]


In [16]:
# comapre > element wise > see all elements > 1 == 4 > False , 2==5 > False , ...
array_one == array_two

array([[False, False, False]])

In [20]:
# work on array > not elements
# see to array are qual or not > (a,b) > compare a with b
np.array_equal(array_one,array_two)

False

In [19]:
# one array compare to itself > True
np.array_equal(array_one,array_one)

True

In [24]:
# work on one array and give you the sum of all elements in that one array > even on axises
np.sum(array_one)

6

In [27]:
array_three = np.array(
    [
        [1,2,3],
        [4,5,6]
    ]
)
# axis 0 > colunms
# axis 1 > row
print(np.sum(array_three)) # sum of all 1+2+3 +...
print(np.sum(array_three,axis=0))
print(np.sum(array_three,axis=1))

21
[5 7 9]
[ 6 15]


In [31]:
# minimum in one array or .max() > element wise
print(array_one.min(),array_one.max())
print(array_two.min(),array_two.max())
print(array_three.min(),array_three.max())

1 3
4 6
1 6


In [33]:
# work on two none similar array
array_four = np.array(
    [
        [1,2,3]
    ]
)

array_five = np.array(
    [
        [4,5,6]
    ]
)

In [54]:
array_four + 1
# 1 will be broadcasted > spread(stretch) one between all elements > 1 > [[1,1,1]]
# broad casting > atumatically
# broad casting > c language(faster)

array([[2, 3, 4]])

In [38]:
# smaller array will be broad casted to bigger array

In [46]:
# if numpy be able to broad cast > ok > two array must be equal in some way
# if not > error
# stretch > 1-horizentally > incrase in colunms(lack row col) in needed cols
# 2-vertically > increase in rows(lack of row) in needed rows

In [48]:
array_six = np.array(
    [
        [1,2,3],
        [7,8,9]
    ]
)
array_six + array_four

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [43]:
array_six + array_five

array([[ 5,  7,  9],
       [11, 13, 15]])

In [49]:
array_seven = np.array(
    [
        [1,2,3],
        [7,8,9]
    ]
)
array_eight = np.array(
    [
        [4,5,6,7]
    ]
)
array_seven + array_eight

ValueError: operands could not be broadcast together with shapes (2,3) (1,4) 

In [52]:
array_nine = np.array(
    [
        [1,2,3]
    ]
)
array_ten = np.array(
    [
        [4],
        [5],
        [6]
    ]
)
array_nine + array_ten

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])