# Universal functions

In [1]:
import numpy as np

In [55]:
# Universal functions > ufuncs > to use vectorization in numpy > run the code in C
# Vetorization > happen when numpy wont run our code by python > run in C lang instead
# to increase the speed of our (program/operation)
# usual work with numpy > array > just have one type data
# but list or tuple in python > different data types

In [11]:
# create array with numpy > all int or all float or all str ... > all from one type
array_one = np.array([1,2,3])
# python list :
list_ = [1,1.2,'parsa',True]
# python list and numpy array > operation > different in speed to run
# python > dynamic type lang > must to run an operation on elements of a list >
# sury all element type one by one then do a process
# but in numpy array > all one type data > no need to sury elements one by one and thier
# type and do operations directly > give to C lang > incease the speed of operation

In [12]:
# Note : in numpy arrays we are not allowed to use different data types and store in
# one array > increased speed

In [138]:
# take an array in python and sum its elements
# create an array with arange > 0 to 9999
# sum the elements > 1 + 2 + ... + 9999
# for in python run this code > low speed >>>
# numpy recommendaton > dont use python tools > use vectorization(give the code
# to C lang and increase the speed) > use ufuncs(all vectorization will be done by ufuncs)
total = 0
for i in np.arange(10000) :
    total += i    
print(total)

49995000


In [23]:
# .add() > plus two arrays
# .subtract() > minus to arrays
# these are element wise
# all logical , comparison operations in numpy > ufuncs > incease speed

In [136]:
np.sum(np.arange(10000))
# will run in C lang > vectorized > inceased speed

49995000

In [27]:
array_two = np.array([1,2,3])
array_three = np.array([4,5,6])

In [35]:
# in python(less speed)
print(array_two+array_three)
# ufuncs > in C(more speed)
# np.add() > add two arrays and return the answer(elenment wise)
# 1 + 4 , 2 + 5 , 3 + 6
print(np.add(array_two,array_three))
print(np.add(array_three,array_two))
# both same result , different speed

[5 7 9]
[5 7 9]
[5 7 9]


# Methods for unfuncs

In [41]:
# To change ufuncs behaviour > on one ufunc
# ufunc.reduce() > decrease needed dimention for array by one
# decrease need arrays to do an operation by 1
# not working elemrnt wise
# e.g > sum elements of one array > 1 + 2 + 3
# np.add(a,b) > is ufunc > need two arrays > array a + array b (element wise / b + a)
# np.add.reduce(a) > need one array > not element wise > a + a
np.add.reduce(array_two)

6

In [44]:
# ufunc.accumualte() > do operation on elements one by one and give the results to
# next operation and use there
# sum to themselves and add the result to next
# 1 , 2 , 3 > 1+2 = 3 > 3 + 3 = 6
# one element add to itself > that element > 1 + 1 = 1
np.add.accumulate(array_two)

array([1, 3, 6])

In [52]:
# ufunc.outer(a,b) > existing elemsnts > as a pair(x,y) > do operations > need two arrays
# combination of elements > one elements to all elemnts will be added
# 1 + 4 , 1 + 5 , 1 + 6
# 2 + 4 , 2 + 5 , 2 + 6
# 3 + 4 , 3 + 5 , 3 + 6
np.add.outer(array_two,array_three)

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])