# Structured arrays

In [1]:
import numpy as np

In [5]:
# When we want to store different data in one array > store data in different ways
# normal arrays : just store one data type > if we store different data types as posssible
# as it is < numpy would convert them to eachother > to make all from one type

In [7]:
# store info users
# normal way : create multiple arrays for each info to stoer
# usernames :
name = np.array(['ali','parsa','mohammad'])
# user ages :
age = np.array([20,23,19])
# problem : in real world because of large number of arrays and elements , it would hard 
# to find out which element relate to which one > solution : structured array(numpy
# wouldnt convert them itself) > differrent ways to create sturctured arrays

In [19]:
# way 1 : create any array
# first : send your data in different types > must send data like : [(),(),(),...] or
# [()]
# second : specify in dtype > ('filed_name/first/sencond/... field','datatype')
# like : [()] , [(),(),...]
# 'U10' > str
# 'i4' > int
# 'f4' > float
# e,g : 'parsa' > first filed , 19 is second field 
name_age_weight = np.array([('parsa',19,40.0),('ali',20,45.0)],
                          dtype=[('name','U10'),('age','i4'),('weight','f4')])
name_age_weight

array([('parsa', 19, 40.), ('ali', 20, 45.)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f4')])

In [32]:
# create an empty array and give it data all the time : way 2
# see index one of array and its contents
name_age_weight[1]

('ali', 22, 45.)

In [28]:
# see the value which are related to filed named 'age'
name_age_weight['age']

array([19, 20])

In [31]:
# change all the values with which are related to age
name_age_weight['age'] = 22

In [30]:
name_age_weight

array([('parsa', 22, 40.), ('ali', 22, 45.)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f4')])

In [34]:
# have the data and merge them
print(name)
print(age)

['ali' 'parsa' 'mohammad']
[20 23 19]


In [42]:
total_array = np.zeros(3) # create an empty array filled by zero
# wht 3 : cause we got 3 elements in name and age array(depened on your array can be changed)
total_array

array([0., 0., 0.])

In [56]:
# in dtype > specify > how you want your filed be like ?
# dtype > a dict > {key:value} > key cant be like array name and they are constant
# like : 'names' > fileds , 'formats' > formats will be stored
# value > tuple > ('your field name','your filed name',...) > filed name can be 
# similat to array name or not
# 'formats' : () > tuple> use numpy scaler or these :
# formats > what kind of data you wnat store / support
# each number befor letter = 8 bit
# 4 byte > 32 bit
# 1 byte > 8 bit
# string : 'U' > unicode string > 'Ux' > totla character will be stored : x
# if char more than x > wont store the rest > store up to x > not store more than x
# store : bytes > 'b' , singed integer > 'i' : 'i4' > i 4 byte = numpy int 32(np.int32) 
# unsigned integer > 'u' : 'u1' > np.uint8
# float > 'f8' > np.int64
total_array = np.zeros(3,dtype={'names':('name','age'),'formats':('U10','i4')})
# use numpy scalers
# total_array = np.zeros(3,dtype={'names':('name','age'),'formats':(tuple(
# np.srt_,10),'i4')})
# np.str_ > store string > (np.str_,x) > x is max number of chars
total_array

array([('', 0), ('', 0), ('', 0)],
      dtype=[('name', '<U10'), ('age', '<i4')])

In [61]:
# filling array
# array_name['filed_name'] = value/array name
total_array['name'] = name
total_array['age'] = age

In [62]:
# merge data together and wont change the data type
total_array

array([('ali', 20), ('parsa', 23), ('mohammad', 19)],
      dtype=[('name', '<U10'), ('age', '<i4')])

In [58]:
# you can also specify dtype or different data type along side

In [64]:
# access data > use indexing
print(total_array[0])
print(total_array[0][0])
print(total_array[0][1])

('ali', 20)
ali
20


In [67]:
# condition in structured array to show data under an specific condition
total_array[total_array['age']>=20]

array([('ali', 20), ('parsa', 23)],
      dtype=[('name', '<U10'), ('age', '<i4')])

# Record array

In [69]:
# is the structured array(exactly the same> no difference)
# but access fields using attributes instead of index
# more comfortable
# np.rec.array() > send data in tuple and specify dtypes
# data > [()] / [(),(),...]
# dtype > [('field_name','data type')]