# Random Sampling

In [2]:
# In numpy we have a module to create random numbers or arrays. Numpy used to use RandomState to do this, but now it uses BitGenerator and
# Generator, but it's still usable in old documents and old versions. However no new features will be added to that.
# Random generator includes new methods
# But the Legacy Random generator icludes old ones
# New version : import default_rng from numpy.random and create an instance From that. And it is a number generator and access to those methods
# by using that instance
# Old version : import random module directly from numpy and access directly to its methods
# For example : random.standard_normal(number)

In [3]:
import numpy as np

# Old version

In [12]:
# Make random numbers
# This makes random integers numbers and take a number as its maximum which means between 0 to maximun
# Creates a random number
# np.random.randint(a) means a random number between 0 and a-1(a is not concluded)
np.random.randint(9)

4

In [19]:
# You can also have a range > (minimum,maximum) > maximum is not concluded
# This gives a random number between minimum and maximum-1
np.random.randint(1,20)

16

In [36]:
# Even you can send the third parameter which means how many numbers you want in that range
# np.random.randint(minimum,maximum,counts)
np.random.randint(1,20,3)

array([ 7,  7, 19], dtype=int32)

In [51]:
# You can define the shape
# a row(s) times b column(s) > (a,b)
np.random.randint(1,20,(5,2))

array([[14,  2],
       [12, 10],
       [ 5, 17],
       [ 4, 12],
       [15, 16]], dtype=int32)

# New version

In [54]:
# Create a variable and you can name it whatever you want
# This gives you a generator and creates random numbers with it and it has different methods
# rng is an instance
rng = np.random.default_rng()

In [61]:
# Create random integer numbers > like .int()
# rng.integers(low)
# If you just send low, it will be considered as maximum and from 0 to low will pick a random integer number
rng.integers(9)

np.int64(8)

In [63]:
# If you send two number > the first is minimum and the second is maximum
# rng.integers(a,b) > between a and b-1 and b is not included
rng.integers(1,20)

np.int64(3)

In [72]:
# You can send the third parameter as its size which is its shape and it's count of values which will be returned
# This gives you 3 numbers in an array
rng.integers(1,20,size=3)

array([ 1,  5, 18])

In [79]:
# Or send tuple as the third parameter which is for its shape
# Create a random array which has 2 rows and 3 columns and has elements from 1 to 19
rng.integers(1,20,(2,3))

array([[15, 15, 15],
       [ 9, 19, 18]])

In [87]:
# Also it has a dtype parameter which is set on np.int64 > dtype=np.int64 by default
# And you have endpoint which says that the maximum is included or not. And by default is False and it's not included and True means it's included
rng.integers(1,20,(2,3),endpoint=True)

array([[20,  3, 16],
       [11, 13, 11]])

In [91]:
# default_rng has a parameter named seed which is None by default, seed=any numbers you want
# We use seed to initialize the BitGenerator. If we give seed a number, it will no longer gives us random numbers and give us repeated numbers
rng2 = np.random.default_rng(seed=1234)
# Or rng2 = np.random.default_rng(1234)
rng2.integers(1,20,(2,3))
# And at first if we run this, with that seed it gives us some randome numbers but after that
# no matter how many times you run that with that seed , it gives you the same result as it gave you before unless you change the seed!

array([[19, 19, 19],
       [ 8,  4, 18]])

In [93]:
rng2 = np.random.default_rng(seed=2)
rng2.integers(1,20,(2,3))
# seed cannot be negative value or a float

array([[16,  5,  3],
       [ 6,  8, 16]])

### This seed was the problem at first in old versions and there was only generator and all codes and all programmers used just one generator
### In new random version : to work with those generators , we create a seperated instance. Giving seed a value is optional

In [94]:
# In old versions :
np.random.seed(1234)
# This seed affected the main core and caused a big mess in other's code which 
# were generating random values and if someone used a seed , that seed was being over-written for all users's seed

In [95]:
# But now we don't have this problem in new versions , each time we want to use
# random, we take an unused generator from numpy and we make an instance from it

In [96]:
# Create random float numbers between 0 and 1
# If you don't send anything it gives a float , but you can define maximum or minimum as well
rng.random()

0.013888803163718877

In [97]:
# This gives us two random float numbers
rng.random(2)

array([0.99407568, 0.07820303])

In [99]:
# Even size or dimentions with tuples can be given
# 2 rows and 3 columns of floats
# Array with 2 rows and 3 columns of floats
rng.random((2,3))

array([[0.68937121, 0.36416215, 0.76255199],
       [0.05111414, 0.52358424, 0.04409299]])

In [100]:
# Or nested array :
# We have two rows and each one has 3 rows and 4 columns
# It has dtype=float64 by default , but it can be changed
rng.random((2,3,4))

array([[[0.79115678, 0.49251173, 0.48494567, 0.15683208],
        [0.20842799, 0.32917676, 0.34525254, 0.73538511],
        [0.69214324, 0.54779718, 0.58227391, 0.93192593]],

       [[0.76247175, 0.38448445, 0.50856307, 0.83797158],
        [0.5257431 , 0.15446164, 0.94709127, 0.79679337],
        [0.94387036, 0.87515999, 0.71327235, 0.25504393]]])

In [104]:
# .choice(a) takes an array and from that array return its elements randomly
rng.choice([1,2,3,4,5,6])

np.int64(5)

In [105]:
# You can even give the size of returned value
# (a,b) > a row(s) and b column(s)
rng.choice([1,2,3,4,5,6],size=(2,2))

array([[6, 1],
       [6, 1]])

In [106]:
# It has replace parameter which is True by default
rng.choice([1,2,3,4,5,6],size=(3,4))
# We have 12 numbers here but in the original array we have 6 numbers
# This is what replace does , and it duplicates some values to fulfill the given size with limited data

array([[5, 5, 4, 6],
       [6, 6, 2, 5],
       [5, 3, 1, 1]])

In [107]:
# What happens if we set replace as False ?
rng.choice([1,2,3,4,5,6],size=(3,4),replace=False)
# It returns an error because the size and the number of total values of original array are not the same
# We have 6 numbers but we want 3 x 4 = 12 numbers

ValueError: Cannot take a larger sample than population when replace is False

In [109]:
# But this works well. 6 numbers in original array = 3 x 2 as size
# If you set replace False, choose the size carefully > the multiple of rows and columns must be equal or less than the total number of elements
rng.choice([1,2,3,4,5,6],size=(3,2),replace=False)

array([[1, 2],
       [4, 3],
       [5, 6]])

In [113]:
# You can even define the chance of selection for each element
# the sum of chances must be 1 ,these numbers are float
# You should pick a chance for each element and one by one in order
# 0 means no chance and 1 means 100 chance
rng.choice([1,2,3,4,5,6],size=(2,2),p=[0,0,0,1,0,0])
# This returns only 4 because the chance of others is 0

array([[4, 4],
       [4, 4]])

In [114]:
# This returns random bytes and just takes a length as its parameter
# 3-btye value will be returned
rng.bytes(3)

b'\xfajf'

### Shuffle vs Permutation

In [154]:
# .shuffle() takes an array and rearrange its elements from the beginning
# And it changes the array and return nothing but previous methods return a new array
# By default axis=0 and it means that it just shuffles the rows
# axis=1 > shuffle thecolumns
# to return the array do this :
array_one = np.array(
    [
        [1,2,3],
        [4,5,6]
    ]
)
rng.shuffle(array_one)
array_one

array([[1, 2, 3],
       [4, 5, 6]])

In [153]:
array_two = np.array(
    [
        [1,2,3],
        [4,5,6]
    ]
)
rng.shuffle(array_one,axis=1)
array_two

array([[1, 2, 3],
       [4, 5, 6]])

In [158]:
# permutation > return a new array and do not chanhe the original array
# But like shuffle rearrange the elements
array_three = np.array(
    [
        [1,2,3],
        [4,5,6]
    ]
)
print(rng.permutation(array_three))
print('--------------')
print(array_three)

[[1 2 3]
 [4 5 6]]
--------------
[[1 2 3]
 [4 5 6]]
