# Array(part 1)

In [1]:
import numpy as np

In [3]:
"""
In 1D-array : numpy.array().shape > (number of elements in array,) > axis 1 is column > just one raw
Example : () > 1 element , (2,) > 2 elements , ...

More thant one dimention(= axis) > axis 0 : number of raws and axis 1 > number of colunms
and axis 2 > deepth > (raw,column,deepth) ~ (axis 0,axis 1,axis 2)

rule : Shape >= 0
"""

'\nIn 1D-array : numpy.array().shape > (number of elements in array,) > axis 0 > just one raw\nExample : () > 1 element , (2,) > 2 elements , ...\n\nMore thant one dimention(= axis) > axis 0 : number of raws and axis 1 > number of colunms\nand axis 2 > deepth > (raw,column,deepth) ~ (axis 0,axis 1,axis 2)\n\nrule : Shape >= 0\n'

In [4]:
# Can't store more than one element without () or []
array_one = np.array(22) # no dimention
array_two = np.array([1,2,3])
array_three = np.array((4,5,6))

In [5]:
array_one

array(22)

In [6]:
array_two

array([1, 2, 3])

In [7]:
array_three

array([4, 5, 6])

In [8]:
print(array_one,type(array_one),array_one.ndim,array_one.shape)
print(array_two,type(array_two),array_two.ndim,array_two.shape)
print(array_three,type(array_three),array_three.ndim,array_three.shape)

22 <class 'numpy.ndarray'> 0 ()
[1 2 3] <class 'numpy.ndarray'> 1 (3,)
[4 5 6] <class 'numpy.ndarray'> 1 (3,)


In [9]:
# Can't write as below(no matter use [] or ()) :
array_four = np.array(
    [1,2,3],
    [4,5,6]
    
)
print(array_four.ndim,array_four.shape)

TypeError: Field elements must be 2- or 3-tuples, got '4'

In [13]:
# The right way to do this is :
array_five = np.array([
    [1,2,3],
    [4,5,6]
])
print(array_five.ndim,array_five.shape)

2 (2, 3)


In [15]:
array_six = np.array([
    [
        [1,2,3],
        [4,5,6]
    ]
])
print(array_six.ndim,array_six.shape)

3 (1, 2, 3)


In [16]:
array_seven = np.array([])

In [17]:
array_seven.ndim

1

In [18]:
array_seven.shape

(0,)

In [19]:
array_eight = np.array(
    [
        [1,2],
        [3,4],
        [5,6]
    ]
)

In [20]:
array_eight.shape

(3, 2)

In [21]:
array_nine = np.array([1,2.3])

In [22]:
array_nine

array([1. , 2.3])

In [23]:
array_ten = np.array([1,'parsa'])

In [24]:
array_ten

array(['1', 'parsa'], dtype='<U21')

In [25]:
array_eleven = np.array([1,True])

In [26]:
array_eleven

array([1, 1])

In [27]:
array_twelve = np.array(['parsa',True])

In [28]:
array_twelve

array(['parsa', 'True'], dtype='<U5')

In [29]:
array_thirteen = np.array([1,2,3])

In [30]:
array_thirteen.dtype

dtype('int64')

In [31]:
array_fourteen = np.array([1,2,3],np.uint8)

In [32]:
array_fourteen

array([1, 2, 3], dtype=uint8)

### Example

In [35]:
a = np.array(
    [
        [
            [
                [
                    [1,2,3,4,5,6],
                    [7,8,9,10,11,12],
                    [13,14,15,16,17,18],
                    [19,20,21,22,23,24],
                ]
            ]
        ]
    ],dtype=np.uint8
)
print("Shape of arraya : ",a.shape)
print("Dimention(s) : ",a.ndim)
print("Raws :",a.shape[3])
print("Colunms :",a.shape[4])
print("Elements : ",a.shape[3]*a.shape[4])
print("Dtype : ",a.dtype)
# By indexig you can access to any specific element
print("First raw : ",a[0][0][0][0])
print("Second raw : ",a[0][0][0][1])
print("Third raw : ",a[0][0][0][2])
print("Fourth raw : ",a[0][0][0][3])

Shape of arraya :  (1, 1, 1, 4, 6)
Dimention(s) :  5
Raws : 4
Colunms : 6
Elements :  24
Dtype :  uint8
First raw :  [1 2 3 4 5 6]
Second raw :  [ 7  8  9 10 11 12]
Third raw :  [13 14 15 16 17 18]
Fourth raw :  [19 20 21 22 23 24]
