# Array(part 2)

In [1]:
import numpy as np

### .array() arguments

In [2]:
# agruments :(default values) > will be in most methodes to create arrays
# 1- cpoy=True 
# 2- order= 'K'
# 3- subok=True

In [7]:
# copy > default = True > if for creating an array we use another array
# either return previous array or create a new array
array_one = np.array([1,2,3]) # > # np.array([#python list]) > convert python list to array
array_one

array([1, 2, 3])

In [8]:
# create another array from previous array 
# every thing will be ok till we change sth in second array
array_two = np.array(array_one)
array_two

array([1, 2, 3])

In [9]:
array_two[0] = 22

In [13]:
# changed at index 0
array_two

array([22,  2,  3])

In [15]:
# no change > because by default > copy = True
# take a copy from first array and create a new array > dont use first array
# if False > will use first array
array_one

array([1, 2, 3])

In [20]:
array_three = np.array([1,2,3])
# chanege value of copy in sencond array not first one
# False > no need to take copy from first array and refer the second array to 
# firt array
# copy > creating array from another array > return first array or 
# create a new one
array_four = np.array(array_three,copy=False)
array_four[0] = 33
print(array_three)
print(array_four)

[33  2  3]
[33  2  3]


In [37]:
# subok > default > Flase > dont use last class
# True > use the class > in second array not forst one
# for creating an array use another array > use the class of first array or
# return a new ndarray
# masked_array([python_list]) > convert python list to array
# you can incease the dimentions(optional)
import numpy.ma as ma
masked_array = ma.masked_array([1,2,3]) # type is masked array
array = np.array(masked_array) # type is normal array
print(masked_array,type(masked_array))
print(array,type(array))

[1 2 3] <class 'numpy.ma.core.MaskedArray'>
[1 2 3] <class 'numpy.ndarray'>


In [40]:
masked_array

masked_array(data=[1, 2, 3],
             mask=False,
       fill_value=999999)

In [41]:
array

array([1, 2, 3])

In [39]:
array_ = np.array(masked_array,subok=True)
print(type(array_))
print(array_)

<class 'numpy.ma.core.MaskedArray'>
[1 2 3]


In [42]:
array_

masked_array(data=[1, 2, 3],
             mask=False,
       fill_value=999999)

In [48]:
# ndmin = 0 > spicify the minimum dimention
array_five = np.array([1,2,3])
print(array_five.ndim)
array_five_ = np.array([1,2,3],ndmin=4) # the minimum d to have is ndmin > if
# the array hasnt > will automatically chanage the d to minimum value
print(array_five_.ndim)
print(array_five_)

1
4
[[[[1 2 3]]]]


In [72]:
# order > four vaues > 'K'(default) , 'A' , 'C' , 'F'
# 'C' & 'F' > important
# usng numpy > two lang to operate > C and Fortran > How to save data in mem is
# different in these two lang
# 2d array
array_six = np.array( 
    [
        [1,2,3],
        [4,5,6]
    ]
)
print(array_six)
# 2d array cant be stored in mem > memory is linear space > and convert 2d to one line
# How ? store row by row(row major) / store colunm by colunm(column major)
# C > (row major)
# Fortran > (column major)
# depend on : use numpy along side which lang
# Normal > store like C > (row major) > 'C'
# return nothing > means it was ok but the storing format in mem changed
# How to calculated(size) is changed
# store memory which stored in ram : > return two numbers(array was two d) >
# count of numbers that will be showned = number of dimention
# x > number of items * .itemsize > in 'C' > row major > in each raw 3 item
# each item is 4 byte > x = > 3 * 4 = 12
# y > columns will store single > each col has one item and each item is 4 byte
# y > 1 * 4 = 4
# (x(row),y(col))
# 'C' > each row use x bytes
# 'C' > each col use y bytes
print(array_six.itemsize) # the size which each item(number) will occupy in memory
# in byte
print(array_six.strides)

[[1 2 3]
 [4 5 6]]
4
(12, 4)


In [74]:
# 2d array
array_six_ = np.array([
        [1,2,3],
        [4,5,6]
    ],order='F')

# 'F' > column major > each col has 2 items and each item is 4 byte > y = 2 * 4 = 8
# each row has 1 item and each item is 4 byte > x = 1 * 4 = 4
# 'F' > each row use x bytes
# 'F' > each col use y bytes
print(array_six_.strides)

(4, 8)


In [75]:
# if we only work with python no matter which order we use
# use default
# 'K' > the program itself will understand whcih storing mthof to use > between 'F' and 'C'
# the more is similar to each one , use thar one
# 'A' > if use 'F' is 'F' is not enter > use 'C'