# Sorting and searching and counting

In [1]:
import numpy as np

In [12]:
# sorting , searching , counting arrays
username = ('Parsa','Ali','Parsa') # tuple
first_name = ('Rezaifar','Ali','Ghasemi') # tuple
array_one = np.array([3,1,2,6,7,0,8,10]) # 1d
array_two = np.array( #2d
    [
        [1,4,2],
        [3,1,5]
    ]
)

In [4]:
# to sort data
# sort > 1-np.sort() > create a new array > give u a copy of that
# 2-ndarray.sort()(on the ndarray call sort) > change the main array
# np.sort(array_name,axis=-1) > default > axis -1 for both way
# axis=-1 > bring last axis
# colum > axis is 0 and rows > axis 1
np.sort(array_two)

array([[1, 2, 4],
       [1, 3, 5]])

In [5]:
print(array_two.sort())
# ndarray.sort(axis=-1)
# Nothig will be returned but the main array is changed
print(array_two)

None
[[1 2 4]
 [1 3 5]]


In [6]:
# change axis
# sort based on asix 0
np.sort(array_two,axis=0)

array([[1, 2, 4],
       [1, 3, 5]])

In [16]:
# .lexsort(keys,axis=-1) > sort based on some keys > default
# axis = -1 > use last axis
# keys > tuples
# send keys to sort based on them
# np.lexsort((tuple - to send keys/(first order),(second order),...))
# sort using last key move to left most > use second key and then use first key
# when to change > when in last key there is repetitive items > and not able to use
# its key and use next key > can sort not repetives but not repetiives > use first key
# username > hast two same items can use its key then use next field(first_name)
# How it works : look at last tuple > see items in tuple
# sort based on order of letters > A is first then P > A is 1
# Two p > are qual > not woking with them
# use firsy key > based on palce of letters
# Dont use repetitve items in first tuple > cause ordered first index 1 in first tuple
# take some keys > order base on them > from end to start
np.lexsort((first_name,username))

array([1, 2, 0], dtype=int64)

In [22]:
# .argsort(array,axis=-1,kind=None,order=None)
# return used indices due to ordering an array
# show if the array get ordered what its indices would be like?
np.argsort(array_one)
# result > indices of elements in the array
# e.g > 0 is index 5

array([5, 1, 2, 0, 3, 4, 6, 7], dtype=int64)

In [25]:
# searching > searching in arrays
# np.searchsorted(a,v,side='left',sorter=None) > default
# a is sorted array
# v is value > where to put this value to not conflict with the order of array
# sort array > np.asort(array name)
sorted_array = np.sort(array_one)
sorted_array

array([ 0,  1,  2,  3,  6,  7,  8, 10])

In [30]:
np.searchsorted(sorted_array,4)
# place the value 4 in index 4 to not change the order of array

4

In [29]:
sorted_array

array([ 0,  1,  2,  3,  6,  7,  8, 10])

In [33]:
# np.argmax(a,axis=None,out=None,*,keepdims=<no value>)
# return the index of biggest number
# axis = None > search all axis
np.argmax(array_one)
# np.argmi() > what do you think this method do :)

7

In [34]:
np.argmin(array_one)

5

In [42]:
np.mod(array_one,3)
# will divide all array elements one by one from start to end > and return residue
# np.mod(array,number)  ~ array element % number

array([0, 1, 2, 0, 1, 0, 2, 1], dtype=int32)

In [43]:
# for seaching we can use conditions
# np.extract(condition,your array)
# base on thar condition > will search > return elements of array
# np.mod(a,b) > divide > a / b  
np.extract(np.mod(array_one,3) == 0,array_one)

array([3, 6, 0])

In [46]:
# np.nonzerp(array) > return value indices which arent 0
# 0 is not just 0 > use a True or False
np.nonzero(array_one)
# insead of giving array directly to np.nonzero() > justify a condition

(array([0, 1, 2, 3, 4, 6, 7], dtype=int64),)

In [48]:
array_one > 3
# will compare all array elements one by one in this condition and see whether they are 
# True(in condition) or Flase(out of condition)

array([False, False, False,  True,  True, False,  True,  True])

In [54]:
# insead of giving array directly to np.nonzero() > justify a condition
# array containing True and Flase and give this array to np.nonzero()
# Flase > 0 , not calculated > dont show in resut
# True > show them in result
# just bring those are in condition
# return indices
np.nonzero(array_one>3)

(array([3, 4, 6, 7], dtype=int64),)

In [56]:
# np.count_nonzero(a[,axis,keepdims])
# count those are not zero > cp all values != 0
np.count_nonzero(array_one)

7