# Masked arrays

In [1]:
import numpy as np
# import the module
import numpy.ma as ma

In [6]:
# masked arrays > some elements of array will be masked(covered)
# seperated module > numpy.ma
# may some elements of data does not exist(missing) or invalid data in it > not operate 
# with this arrays
# for masking we use Booleans > which element we want and which we dont > True & False
# False > that element is valid > stay um-masked
# True > ''     ''     isnt valid > will be masked

In [13]:
# create array
array_one = np.arange(-3,5) # will create a 1D array by default
array_one

array([-3, -2, -1,  0,  1,  2,  3,  4])

In [15]:
array_two = np.array(
    [
        [1,2,3],
        [4,np.nan,6] # .nan > invalid value > not a number(constant in numpy)
        # .nan > will convert other values to float
        # np.nan > nan
    ]
)
array_two

array([[ 1.,  2.,  3.],
       [ 4., nan,  6.]])

In [16]:
# becauuse of nan no operation or method will work as well is should be
# nan > invalid > not working
array_two.sum()

nan

In [28]:
# we dont need negative nums > mask them
# ""  ""    ""   nan value > mask it > cover it > nothing in it


# create a new array to store mask
# .masked_array(your_array,mask=[]) > create a masked array
# mask parameter will be a list > which elements you want to mask (in order)
# send True(or 1) or False(or 0) > e.g > for : 1 > valid > 0(not be masked)
# for 2 > valid > 0 .... and for nan > invalid(will be masked) > 1
# input True or False manually
masked_array = ma.masked_array(array_two,mask=[0,0,0,0,1,0])
masked_array

masked_array(
  data=[[1.0, 2.0, 3.0],
        [4.0, --, 6.0]],
  mask=[[False, False, False],
        [False,  True, False]],
  fill_value=1e+20)

In [27]:
# the ma module will esure that masked elements will not be involved in operatins and
# methods
masked_array.sum()

16.0

In [29]:
# if array were to big we couldnt write True or False manually
# .masked_invalid(array) > just send array > automatically will make invalid elements
masked_array2 = ma.masked_invalid(array_two)
masked_array2

masked_array(
  data=[[1.0, 2.0, 3.0],
        [4.0, --, 6.0]],
  mask=[[False, False, False],
        [False,  True, False]],
  fill_value=1e+20)

In [30]:
masked_array2.sum()

16.0

In [31]:
array_one

array([-3, -2, -1,  0,  1,  2,  3,  4])

In [35]:
# mask(True) - nums
# .masked_where(send an if statement,your_array) > mask base on a if cluase
# masked_where(your_array....,array_name)
# will mask data that are in our if
masked_array3 = ma.masked_where(array_one<=0,array_one)
masked_array3

masked_array(data=[--, --, --, --, 1, 2, 3, 4],
             mask=[ True,  True,  True,  True, False, False, False, False],
       fill_value=999999)

In [36]:
masked_array3.sum()

10

In [ ]:
# send values > and these values will be masked
# .masked_values(your_array,value(s))
masked_array4 = ma.masked_values(array_one,0)
mas